server:
  port: 8081
spring:
  application:
    name: microservice-provide-category
  jpa:
    show-sql: true
    database: mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///gmalldb?serverTimezone=UTC
    username: root
    password: root
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/