server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
      - id: payment_rout
        uri: lb://payment-server
        predicates:
            - Path=/payment/**
      discovery:
        locator:
          enabled: true