server:
  port: 80
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
        server-addr: 192.168.61.110:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"