logging:
  level:
    com.husky: trace
  file:
    path: /spring/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: registyCenter