spring:
  application:
    name: user-info-eurekaclient
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.61.110:3306/gmall?serverTimezone=UTC
    username: root
    password: root
server:
  port: 8081
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.husky.userinfoeureka2.entity
  mapper-locations: classpath:mapper/userinfo.xml