server:
  port: 8762
spring:
  application:
    name: eureka-server-slave
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/