server:
  port: 8084
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
zuul:
  routes:
    user:
      url: http://localhost:8080
      path: /user/all
